import Image from 'next/image';
import {ArrowRightLeft, Pencil, Plus, Trash2} from 'lucide-react';
import {TransferForm, type TransferFormRow} from '@/components/admin/transfer-form';
import {requireAdmin} from '@/src/lib/supabase/admin';
import {createTransfer,deleteTransfer,updateTransfer} from './actions';

type Row=TransferFormRow;
export default async function AdminTransfersPage({searchParams}:{searchParams:Promise<{result?:string}>}){const query=await searchParams;const{supabase}=await requireAdmin();const{data,error}=await supabase.from('transfers').select('*').order('season',{ascending:false}).order('display_order',{ascending:true});const rows=(data??[]) as Row[];return <><div className="max-w-3xl"><div className="eyebrow">Deal portfolio</div><h1 className="font-display text-4xl font-semibold text-white sm:text-5xl">Manage transfers</h1><p className="mt-4 text-lg leading-8 text-mist">Publish completed moves and feature selected top deals.</p></div><Message result={query.result??error?.message}/>
<details className="mt-10 border border-accent/40 bg-panel" open={!rows.length}><summary className="flex cursor-pointer items-center gap-3 p-5 font-display text-xl font-semibold text-white"><Plus className="h-5 w-5 text-blue-400"/> Add transfer</summary><TransferForm action={createTransfer} label="Create transfer"/></details>
<section className="mt-10"><div className="flex justify-between"><h2 className="font-display text-2xl font-semibold text-white">Transfer records</h2><span className="text-sm text-slate-500">{rows.length} records</span></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{rows.map(row=><article key={row.id} className="overflow-hidden border border-line bg-panel"><div className="grid grid-cols-[145px_1fr]">{row.image_url||row.player_photo_url?<div className="relative min-h-44 bg-[#061426]"><Image src={row.image_url||row.player_photo_url!} alt={row.player_name} fill className="object-contain p-3"/></div>:<div className="flex min-h-44 items-center justify-center bg-blue-950/30"><ArrowRightLeft className="h-10 w-10 text-blue-400"/></div>}<div className="p-5"><div className="flex gap-2"><Badge>{row.is_published?'Published':'Draft'}</Badge>{row.is_top_deal?<Badge>Top deal</Badge>:null}</div><h3 className="mt-4 font-display text-2xl font-semibold text-white">{row.player_name}</h3><p className="mt-2 text-sm text-mist">{row.from_club} {'->'} {row.to_club}</p><p className="mt-2 text-xs uppercase text-blue-300">{row.season} / Order {row.display_order}</p></div></div><details className="border-t border-line"><summary className="flex cursor-pointer items-center gap-2 px-5 py-4 text-xs font-bold uppercase text-blue-300"><Pencil className="h-4 w-4"/> Edit transfer</summary><TransferForm action={updateTransfer} label="Save changes" row={row}/><form action={deleteTransfer} className="border-t border-line p-5"><input type="hidden" name="id" value={row.id}/><button className="inline-flex h-10 items-center gap-2 border border-red-500/50 px-4 text-xs font-bold uppercase text-red-300"><Trash2 className="h-4 w-4"/> Delete transfer</button></form></details></article>)}</div></section></>}
function Badge({children}:{children:React.ReactNode}){return <span className="bg-blue-950/70 px-2 py-1 text-[10px] font-bold uppercase text-blue-300">{children}</span>}
function Message({result}:{result?:string}){if(!result)return null;const ok=['created','updated','deleted'].includes(result);return <p className={`mt-6 border-s-2 px-4 py-3 text-sm ${ok?'border-emerald-500 bg-emerald-500/10 text-emerald-200':'border-red-500 bg-red-500/10 text-red-200'}`}>{ok?`Transfer ${result} successfully.`:decodeURIComponent(result)}</p>}
